@baseUrl = http://localhost:3000/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWxBZGRyZXNzIjoiem4yM0BjYWx2aW4uZWR1IiwiaWF0IjoxNzMzOTQ5MjA2LCJleHAiOjE3MzM5NTI4MDZ9.JMkcdZQcC3Gb_XIboOYvYWR-RhAiKD72h5Q2_OoP8gs
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWxBZGRyZXNzIjoiem4yM0BjYWx2aW4uZWR1IiwiaWF0IjoxNzMzODkwOTU1LCJleHAiOjE3MzQ0OTU3NTV9.yugKPwjjJVLXl53UDeonvdKMJM3TqxhoYL1fPRr75Gw

### login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "emailAddress": "zn23@calvin.edu",
  "password": "swolemate1234"
}

### refresh
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### -----------------------------------

### User: GET
GET {{baseUrl}}/users?gender=male
Authorization: Bearer {{accessToken}}

### User: POST
POST {{baseUrl}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "emailAddress": "test@test.com",
  "username": "test",
  "passwordHash": "test1234"
}

### User: PUT
PUT {{baseUrl}}/users/15
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "emailAddress": "tesft@test.com"
}

### User: DELETE
DELETE {{baseUrl}}/users/36
Authorization: Bearer {{accessToken}}
