import { IUserMatch } from "./interfaces";

export const fakeUsers: IUserMatch[] = [
  { id: "1", name: "John Doe", age: 25, height: "6 ft", weight: "180 lbs" },
  {
    id: "2",
    name: "Jane Doe",
    age: 28,
    height: "5 ft 6 in",
    weight: "150 lbs",
    pending: false,
  },
  {
    id: "3",
    name: "Beyonce",
    age: 22,
    height: "5 ft 7 in",
    weight: "137 lbs",
    pending: false,
  },
  {
    id: "4",
    name: "Tom Cruise",
    age: 27,
    height: "5 ft 7 in",
    weight: "201 lbs",
    pending: false,
  },
  {
    id: "5",
    name: "Jennifer Lopez",
    age: 24,
    height: "5 ft 5 in",
    weight: "120 lbs",
    pending: false,
  },
  {
    id: "6",
    name: "Brad Pitt",
    age: 30,
    height: "6 ft 0 in",
    weight: "203 lbs",
    pending: false,
  },
  {
    id: "7",
    name: "Carrie Underwood",
    age: 26,
    height: "5 ft 3 in",
    weight: "117 lbs",
  },
  {
    id: "8",
    name: "Travis Kelce",
    age: 29,
    height: "6 ft 5 in",
    weight: "250 lbs",
  },
  {
    id: "9",
    name: "Jennifer Lawrence",
    age: 23,
    height: "5 ft 9 in",
    weight: "138 lbs",
  },
  {
    id: "10",
    name: "Patrick Mahomes",
    age: 31,
    height: "6 ft 2 in",
    weight: "225 lbs",
  },
  {
    id: "11",
    name: "Taylor Swift",
    age: 20,
    height: "5 ft 11 in",
    weight: "119 lbs",
  },
  {
    id: "12",
    name: "Sean John Combs",
    age: 27,
    height: "5 ft 10 in",
    weight: "190 lbs",
  },
  {
    id: "13",
    name: "Ariana Grande",
    age: 25,
    height: "5 ft 0 in",
    weight: "104 lbs",
  },
  {
    id: "14",
    name: "Christopher Clark",
    age: 28,
    height: "6 ft 1 in",
    weight: "185 lbs",
  },
  {
    id: "15",
    name: "Samantha Lewis",
    age: 22,
    height: "5 ft 2 in",
    weight: "120 lbs",
  },
  {
    id: "16",
    name: "William Walker",
    age: 26,
    height: "6 ft 3 in",
    weight: "210 lbs",
  },
  {
    id: "17",
    name: "Emily Hall",
    age: 24,
    height: "5 ft 5 in",
    weight: "145 lbs",
  },
  {
    id: "18",
    name: "Joshua Young",
    age: 29,
    height: "5 ft 8 in",
    weight: "165 lbs",
  },
  {
    id: "19",
    name: "Isabella King",
    age: 23,
    height: "5 ft 4 in",
    weight: "130 lbs",
  },
  {
    id: "20",
    name: "Matthew Scott",
    age: 30,
    height: "6 ft",
    weight: "195 lbs",
  },
];

export const fakeMatches = [
  {
    id: "1",
    name: "John Smith",
    message: "Hey, how's your workout going?",
    time: "13.18",
    avatar: require("@/assets/avatars/1.png"),
  },
  {
    id: "2",
    name: "Emily Johnson",
    message: "Want to meet up at the gym later?",
    time: "12.13",
    avatar: require("@/assets/avatars/2.png"),
  },
  {
    id: "3",
    name: "Michael Brown",
    message: "Thanks for the protein shake recipe!",
    time: "13.31",
    avatar: require("@/assets/avatars/3.png"),
  },
  {
    id: "4",
    name: "Sarah Davis",
    message: "How was your run this morning?",
    time: "11.31",
    avatar: require("@/assets/avatars/4.png"),
  },
  {
    id: "5",
    name: "David Wilson",
    message: "Let's plan our next hiking trip!",
    time: "10.21",
    avatar: require("@/assets/avatars/5.png"),
  },
];

export const fakePendings = [
  {
    id: "1",
    name: "Darlene Steward",
    time: "18.31",
    avatar: require("@/assets/avatars/1.png"),
    status: "Pending",
  },
  {
    id: "2",
    name: "Mike Mazowski",
    time: "16.04",
    avatar: require("@/assets/avatars/2.png"),
    status: "Pending",
  },
  {
    id: "3",
    name: "Lee Williamson",
    time: "06.12",
    avatar: require("@/assets/avatars/3.png"),
    status: "Pending",
  },
  {
    id: "4",
    name: "Ronald Mccoy",
    time: "Yesterday",
    avatar: require("@/assets/avatars/4.png"),
    status: "Pending",
  },
];
