import { IUserMatch } from "./interfaces";

export const fakeUsers = [
  {
    id: "1",
    firstName: "John Doe",
    age: 25,
    typeOfWorkout: "Power Lifter",
    gym: "Gold's Gym",
    city: "New York",
    height: 180,
    weight: 80,
    rating: 4.5,
    isTrainer: true,
    experience: "3+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
    // reviews: ["Great trainer, very knowledgeable!", "Pushes me to do better every day."]
  },
  {
    id: "2",
    name: "Jane Doe",
    age: 28,
    typeOfWorkout: "Yoga",
    gym: "Anytime Fitness",
    city: "Los Angeles",
    height: 168,
    weight: 150,
    rating: 4.0,
    isTrainer: false,
    experience: "2+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
    // reviews: ["The yoga sessions are very calming and refreshing.", "I feel more flexible and focused."]
  },
  {
    id: "3",
    name: "Beyonce",
    age: 22,
    typeOfWorkout: "Dancer",
    gym: "24 Hour Fitness",
    city: "Houston",
    height: 170,
    weight: 137,
    rating: 3.0,
    isTrainer: false,
    experience: "7+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
    // reviews: ["Incredible moves and energy!", "Very motivating and fun to work with."]
  },
  {
    id: "4",
    name: "Tom Cruise",
    age: 27,
    typeOfWorkout: "Action Star Training",
    gym: "Gold's Gym",
    city: "Los Angeles",
    height: 170,
    weight: 201,
    rating: 4.0,
    isTrainer: false,
    experience: "10+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
    // reviews: ["His training routines are intense but rewarding.", "Really focused on strength and endurance."]
  },
  {
    id: "5",
    name: "Jennifer Lopez",
    age: 24,
    typeOfWorkout: "Dance Cardio",
    gym: "Planet Fitness",
    city: "New York",
    height: 165,
    weight: 120,
    rating: 4.5,
    isTrainer: false,
    experience: "1 year of working out",
    matched: false,
    pending: false,
    showMore: false,
    // reviews: ["Fun and engaging workouts.", "Great cardio routines that keep you moving!"]
  },
  {
    id: "6",
    name: "Brad Pitt",
    age: 30,
    typeOfWorkout: "Weight Lifting",
    gym: "Gold's Gym",
    city: "Los Angeles",
    height: 183,
    weight: 203,
    rating: 2.0,
    isTrainer: true,
    experience: "2 years of working out",
    matched: false,
    pending: false,
    showMore: false,
    // reviews: ["Excellent form and technique guidance.", "Really helps with improving lifting strength."]
  },
  {
    id: "7",
    name: "Carrie Underwood",
    age: 26,
    typeOfWorkout: "Running",
    gym: "Local Gym",
    city: "Nashville",
    height: 160,
    weight: 117,
    rating: 3.5,
    isTrainer: false,
    experience: "3+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
    // reviews: ["Great running coach, knows how to push me!", "Very supportive and motivational."]
  },
  {
    id: "8",
    name: "Travis Kelce",
    age: 29,
    typeOfWorkout: "Football Training",
    gym: "YMCA",
    city: "Kansas City",
    height: 196,
    weight: 250,
    rating: 5.0,
    isTrainer: true,
    experience: "12+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
    // reviews: ["Best football trainer, extremely knowledgeable.", "His drills really improve my agility."]
  },
  {
    id: "9",
    name: "Jennifer Lawrence",
    age: 23,
    typeOfWorkout: "General Fitness",
    gym: "Anytime Fitness",
    city: "Louisville",
    height: 175,
    weight: 138,
    rating: 4.0,
    isTrainer: false,
    experience: "4 years of working out",
    matched: false,
    pending: false,
    showMore: false,
    // reviews: ["Excellent trainer with a great attitude.", "Training sessions are challenging and fun."]
  },
  {
    id: "10",
    name: "Patrick Mahomes",
    age: 31,
    typeOfWorkout: "Quarterback Training",
    gym: "Lifetime Fitness",
    city: "Kansas City",
    height: 188,
    weight: 225,
    rating: 5.0,
    isTrainer: true,
    experience: "8+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
    // reviews: ["Amazing coach, very professional.", "Definitely helped with improving my accuracy."]
  },
  {
    id: "11",
    name: "Taylor Swift",
    age: 20,
    typeOfWorkout: "Dance",
    gym: "Local Dance Studio",
    city: "Nashville",
    height: 180,
    weight: 119,
    rating: 4.5,
    isTrainer: false,
    experience: "7+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
  },
  {
    id: "12",
    name: "Sean John Combs",
    age: 27,
    typeOfWorkout: "Hip-Hop Dance",
    gym: "24 Hour Fitness",
    city: "New York",
    height: 178,
    weight: 190,
    rating: 4.0,
    isTrainer: false,
    experience: "4+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
  },
  {
    id: "13",
    name: "Ariana Grande",
    age: 25,
    typeOfWorkout: "Cardio",
    gym: "Equinox",
    city: "Boca Raton",
    height: 152,
    weight: 104,
    rating: 1.0,
    isTrainer: false,
    experience: "5+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
  },
  {
    id: "14",
    name: "Christopher Clark",
    age: 28,
    typeOfWorkout: "Bodybuilding",
    gym: "Gold's Gym",
    city: "Los Angeles",
    height: 185,
    weight: 185,
    rating: 4.0,
    isTrainer: true,
    experience: "2+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
  },
  {
    id: "15",
    name: "Samantha Lewis",
    age: 22,
    typeOfWorkout: "Yoga",
    gym: "Local Yoga Studio",
    city: "San Francisco",
    height: 157,
    weight: 120,
    rating: 1.5,
    isTrainer: false,
    experience: "3+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
  },
  {
    id: "16",
    name: "William Walker",
    age: 26,
    typeOfWorkout: "Mixed Martial Arts",
    gym: "MMA Gym",
    city: "Chicago",
    height: 190,
    weight: 210,
    rating: 3.5,
    isTrainer: true,
    experience: ">1 year of working out",
    matched: false,
    pending: false,
    showMore: false,
  },
  {
    id: "17",
    name: "Emily Hall",
    age: 24,
    typeOfWorkout: "Running",
    gym: "Local Gym",
    city: "Atlanta",
    height: 165,
    weight: 145,
    rating: 4.0,
    isTrainer: false,
    experience: ">1 year of working out",
    matched: false,
    pending: false,
    showMore: false,
  },
  {
    id: "18",
    name: "Joshua Young",
    age: 29,
    typeOfWorkout: "Weight Training",
    gym: "Gold's Gym",
    city: "Seattle",
    height: 173,
    weight: 165,
    rating: 4.5,
    isTrainer: false,
    experience: "3+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
  },
  {
    id: "19",
    name: "Isabella King",
    age: 23,
    typeOfWorkout: "General Fitness",
    gym: "Anytime Fitness",
    city: "Miami",
    height: 163,
    weight: 130,
    rating: 3.5,
    isTrainer: false,
    experience: "5+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
  },
  {
    id: "20",
    name: "Matthew Scott",
    age: 30,
    typeOfWorkout: "Strength Training",
    gym: "Local Gym",
    city: "Denver",
    height: 183,
    weight: 195,
    rating: 5.0,
    isTrainer: false,
    experience: "4+ years of working out",
    matched: false,
    pending: false,
    showMore: false,
  },
];

export const fakeMatches = [
  {
    id: "1",
    name: "John Smith",
    message: "Hey, how's your workout going?",
    time: "13.18",
    avatar: require("@/assets/avatars/1.png"),
  },
  {
    id: "2",
    name: "Emily Johnson",
    message: "Want to meet up at the gym later?",
    time: "12.13",
    avatar: require("@/assets/avatars/2.png"),
  },
  {
    id: "3",
    name: "Michael Brown",
    message: "Thanks for the protein shake recipe!",
    time: "13.31",
    avatar: require("@/assets/avatars/3.png"),
  },
  {
    id: "4",
    name: "Sarah Davis",
    message: "How was your run this morning?",
    time: "11.31",
    avatar: require("@/assets/avatars/4.png"),
  },
  {
    id: "5",
    name: "David Wilson",
    message: "Let's plan our next hiking trip!",
    time: "10.21",
    avatar: require("@/assets/avatars/5.png"),
  },
];

export const fakePendings = [
  {
    id: "1",
    name: "Darlene Steward",
    time: "18.31",
    avatar: require("@/assets/avatars/1.png"),
    status: "Pending",
  },
  {
    id: "2",
    name: "Mike Mazowski",
    time: "16.04",
    avatar: require("@/assets/avatars/2.png"),
    status: "Pending",
  },
  {
    id: "3",
    name: "Lee Williamson",
    time: "06.12",
    avatar: require("@/assets/avatars/3.png"),
    status: "Pending",
  },
  {
    id: "4",
    name: "Ronald Mccoy",
    time: "Yesterday",
    avatar: require("@/assets/avatars/4.png"),
    status: "Pending",
  },
];
